import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./(e-commerce)/component/Navbar";
import Footer from "./(e-commerce)/component/Footer";



export const metadata = {
  title: "NEXT JS E-COMMERCE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        
      </body>
    </html>
  );
}
